# Lec 01. Tensor Basic

In [1]:
import torch
import numpy as np

In [2]:
torch.__version__

'0.4.1'

In [3]:
# Tensor의 기초적 선언. torch.FloatTensor와 동일. 
x = torch.Tensor(2, 3)
print(x)

tensor([[0.0000, 0.0000, 0.0003],
        [0.0000, 0.0000, 0.0000]])


In [4]:
# Tesnor의 정보 확인
print("Tensor Type : ", x.type())
print("Tensor Size : ", x.size())

Tensor Type :  torch.FloatTensor
Tensor Size :  torch.Size([2, 3])


## Tensor with charateristics

In [5]:
# 0으로 채워진 Tensor 선언
x = torch.zeros(2, 3)
print(x)

tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [6]:
# 0, 1 사이의 랜덤 숫자로 채워진 Tensor 선언
x = torch.rand(2, 3)
print(x)

tensor([[0.1022, 0.5927, 0.2162],
        [0.2476, 0.5216, 0.4157]])


In [7]:
# 평균이 0이고 분산이 1을 따르는 정규분포에서 추출된 값으로 채워진 Tensor 선언
x = torch.randn(2, 3)
print(x)

tensor([[-0.9535,  1.3534, -0.1467],
        [ 0.6547, -0.2610,  0.0446]])


In [8]:
# 대각 행렬 같은 Tensor 선언
x = torch.eye(3, 3)
print(x)

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])


In [9]:
# 0부터 3까지 0.5씩 증가하는 Tensor 선언
x = torch.arange(0, 3, step=0.5)
print(x)

tensor([0.0000, 0.5000, 1.0000, 1.5000, 2.0000, 2.5000])


In [10]:
# 32-bit integer (signed)
c = torch.IntTensor(3,2)
print(c)

tensor([[154574216,     32762],
        [        0,         0],
        [        0,         0]], dtype=torch.int32)


In [11]:
# 32-bit floating point
x = torch.FloatTensor(5,3)
print(x)

tensor([[0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000],
        [0.0745, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000],
        [0.0745, 0.0000, 0.0000]])


## Tensor and Numpy

In [12]:
# numpy 형식의 배열
x = np.array([[1,2,3],[4,5,6]])
print(x, '\n', type(x))

[[1 2 3]
 [4 5 6]] 
 <class 'numpy.ndarray'>


In [13]:
# numpy를 tensor로 변환
xt = torch.from_numpy(x)
print(xt)

tensor([[1, 2, 3],
        [4, 5, 6]], dtype=torch.int32)


In [14]:
# tensor를 numpy로 변환
x = xt.numpy()
print(x, '\n', type(x))

[[1 2 3]
 [4 5 6]] 
 <class 'numpy.ndarray'>


## Tensor Slicing

In [15]:
x = torch.Tensor([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print(x)

tensor([[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.]])


In [16]:
# 모든 원소 출력
x[:, :]

tensor([[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.]])

In [17]:
# 2행부터 출력
x[1:, :]

tensor([[ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.]])

In [18]:
# 2열부터 출력
x[:, 1:]

tensor([[ 2.,  3.,  4.],
        [ 6.,  7.,  8.],
        [10., 11., 12.]])

In [19]:
# 2행, 2열부터 3열까지 출력
x[1:, 1:3]

tensor([[ 6.,  7.],
        [10., 11.]])

In [20]:
# 1행 출력
x[0, :]

tensor([1., 2., 3., 4.])

In [21]:
# x를 1행씩 잘라서 배열로 저장
x_rows = torch.split(x, split_size_or_sections=1, dim=0)   # dim 주의 !!!
print(x_rows)

(tensor([[1., 2., 3., 4.]]), tensor([[5., 6., 7., 8.]]), tensor([[ 9., 10., 11., 12.]]))


In [22]:
x_rows = torch.chunk(x, 3, dim=0)
print(x_rows)

(tensor([[1., 2., 3., 4.]]), tensor([[5., 6., 7., 8.]]), tensor([[ 9., 10., 11., 12.]]))


In [23]:
# x를 2열씩 잘라서 배열로 저장
x_cols = torch.split(x, split_size_or_sections=2, dim=1)
print(x_cols)

(tensor([[ 1.,  2.],
        [ 5.,  6.],
        [ 9., 10.]]), tensor([[ 3.,  4.],
        [ 7.,  8.],
        [11., 12.]]))


In [24]:
x_cols = torch.chunk(x, 2, dim=1)
print(x_cols)

(tensor([[ 1.,  2.],
        [ 5.,  6.],
        [ 9., 10.]]), tensor([[ 3.,  4.],
        [ 7.,  8.],
        [11., 12.]]))


In [25]:
# x_cols의 첫번째 배열 중 특정 부분만 추출하기
torch.masked_select(x_cols[0], torch.ByteTensor([[0,1],[1,0],[0,1]]))

tensor([ 2.,  5., 10.])

## Tensor Merging

In [26]:
# x_rows를 열로 이어 붙이기
torch.cat(x_rows, dim=1)

tensor([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.]])

In [27]:
# x_cols를 쌓아올리기
x_new = torch.stack(x_cols, dim=0)
print(x_new)

tensor([[[ 1.,  2.],
         [ 5.,  6.],
         [ 9., 10.]],

        [[ 3.,  4.],
         [ 7.,  8.],
         [11., 12.]]])


## Tensor Reshaping

In [28]:
x = torch.Tensor([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(x)

tensor([[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.]])


In [29]:
# 4행 3열로 바꾸기
x.view(4,3)

tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.],
        [10., 11., 12.]])

In [30]:
# 2열로 바꾸기
x.view(-1, 2)

tensor([[ 1.,  2.],
        [ 3.,  4.],
        [ 5.,  6.],
        [ 7.,  8.],
        [ 9., 10.],
        [11., 12.]])

In [31]:
print(x)

x2 = x.view(4, 1, -1)
print(x2)
print(x2.size())

tensor([[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.]])
tensor([[[ 1.,  2.,  3.]],

        [[ 4.,  5.,  6.]],

        [[ 7.,  8.,  9.]],

        [[10., 11., 12.]]])
torch.Size([4, 1, 3])


In [32]:
# 차원이 1인 값을 축소
x.view(2, 1, -1).squeeze()

tensor([[ 1.,  2.,  3.,  4.,  5.,  6.],
        [ 7.,  8.,  9., 10., 11., 12.]])

In [33]:
# 차원을 row로 자른 후 저장
x.view(2, 1, -1).squeeze().unsqueeze(dim=1)

tensor([[[ 1.,  2.,  3.,  4.,  5.,  6.]],

        [[ 7.,  8.,  9., 10., 11., 12.]]])

## Tensor for GPU

In [34]:
x = torch.Tensor(2,3)
print(x)

tensor([[0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000]])


In [35]:
# cpu를 gpu로 전환
gpu_x = x.cuda()
print(gpu_x)

tensor([[0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000]], device='cuda:0')


In [36]:
# gpu를 cpu로 전환
x = gpu_x.cpu()
print(x)

tensor([[0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000]])


## Tensor Calculation

In [37]:
x = torch.Tensor([[1,2,3],[4,5,6]])
y = torch.Tensor([[1,1,1],[2,2,2]])
print(x)
print(y)

tensor([[1., 2., 3.],
        [4., 5., 6.]])
tensor([[1., 1., 1.],
        [2., 2., 2.]])


In [38]:
# x와 y의 합
z = torch.add(x, y)
print(z)
print(x+y)

tensor([[2., 3., 4.],
        [6., 7., 8.]])
tensor([[2., 3., 4.],
        [6., 7., 8.]])


In [39]:
# x의 모든 원소에서 2를 뺌
print(x - 2)

# x의 모든 원소에 2를 곱함
print(2*x)

tensor([[-1.,  0.,  1.],
        [ 2.,  3.,  4.]])
tensor([[ 2.,  4.,  6.],
        [ 8., 10., 12.]])


In [40]:
# x의 원소와 y의 원소를 각각 곱함
z = torch.mul(x, y)
print(z)
print(x*y)

tensor([[ 1.,  2.,  3.],
        [ 8., 10., 12.]])
tensor([[ 1.,  2.,  3.],
        [ 8., 10., 12.]])


In [41]:
# x의 원소를 각각 제곱함
z = torch.pow(x, 2)
print(z)
print(x**2)

tensor([[ 1.,  4.,  9.],
        [16., 25., 36.]])
tensor([[ 1.,  4.,  9.],
        [16., 25., 36.]])


In [42]:
# x의 원소에 log를 씌움
z = torch.log(x)
print(z, x.log())

tensor([[0.0000, 0.6931, 1.0986],
        [1.3863, 1.6094, 1.7918]]) tensor([[0.0000, 0.6931, 1.0986],
        [1.3863, 1.6094, 1.7918]])


In [43]:
# x의 원소에 루트를 씌움
z = torch.sqrt(x)
print(z)
print(x.sqrt())

tensor([[1.0000, 1.4142, 1.7321],
        [2.0000, 2.2361, 2.4495]])
tensor([[1.0000, 1.4142, 1.7321],
        [2.0000, 2.2361, 2.4495]])


In [44]:
# x의 원소에 mod 계산
z = x % 2
print(z)

tensor([[1., 0., 1.],
        [0., 1., 0.]])


## Tensor Casting

In [45]:
x.type()

'torch.FloatTensor'

In [46]:
x.type(torch.DoubleTensor)

tensor([[1., 2., 3.],
        [4., 5., 6.]], dtype=torch.float64)

In [47]:
x.type(torch.IntTensor)

tensor([[1, 2, 3],
        [4, 5, 6]], dtype=torch.int32)

## Tensor Statistic

In [48]:
x = torch.Tensor([[-1,2,-3],[4,-5,6],[-4,5,-6],[7,8,9]])
print(x)

tensor([[-1.,  2., -3.],
        [ 4., -5.,  6.],
        [-4.,  5., -6.],
        [ 7.,  8.,  9.]])


In [49]:
x.sum(), x.max(), x.min(), x.var()

(tensor(22.), tensor(9.), tensor(-6.), tensor(29.2424))

In [50]:
# 행을 기준으로 열의 최댓값을 출력
value, index = x.max(dim=0)
value

tensor([7., 8., 9.])

In [51]:
# 행을 기준으로 열의 최소값을 출력
value, index = x.min(dim=0)
value

tensor([-4., -5., -6.])

In [52]:
# 열을 기준으로 각 행을 정렬
value, index = x.sort(dim=1)
value

tensor([[-3., -1.,  2.],
        [-5.,  4.,  6.],
        [-6., -4.,  5.],
        [ 7.,  8.,  9.]])

## Tensor Calculation as Matrix

In [53]:
x = torch.Tensor([[1,1],[2,2]])
y = torch.Tensor([[1,2],[3,4]])
print(x)
print(y)

tensor([[1., 1.],
        [2., 2.]])
tensor([[1., 2.],
        [3., 4.]])


In [54]:
# x와 y의 행렬곱
torch.mm(x, y)

tensor([[ 4.,  6.],
        [ 8., 12.]])

In [55]:
# x와 z의 행렬벡터곱
z = torch.Tensor([1, 2])
torch.mv(x, z)

tensor([3., 6.])

In [56]:
# z와 z의 내적
torch.dot(z, z)

tensor(5.)

In [57]:
# x의 전치(transpose)
x.t()

tensor([[1., 2.],
        [1., 2.]])

In [58]:
# 텐서의 배치 행렬곱
x1 = torch.FloatTensor(3,3,2)
x2 = torch.FloatTensor(3,2,3)

xx = torch.bmm(x1,x2)
print(xx)
print(xx.size())

tensor([[[0.0000, 0.0000, 0.0000],
         [0.0000, 0.0000, 0.0000],
         [0.0000, 0.0000, 0.0000]],

        [[0.0000, 0.0000, 0.0000],
         [0.0000, 0.0000, 0.0000],
         [0.0000, 0.0000, 0.0000]],

        [[0.0000, 0.0000, 0.0000],
         [0.0000, 0.0000, 0.0000],
         [0.0000, 0.0000, 0.0000]]])
torch.Size([3, 3, 3])


In [59]:
# 텐서의 전치
x1.transpose(1, 2).size()

torch.Size([3, 2, 3])

In [60]:
# 고유값, 고유 벡터
print(x)
eigenvalue, eigenvector = torch.eig(x, eigenvectors=True)
print("eigenvalue :", eigenvalue)
print("eigenvector :", eigenvector)

tensor([[1., 1.],
        [2., 2.]])
eigenvalue : tensor([[0.0000, 0.0000],
        [3.0000, 0.0000]])
eigenvector : tensor([[-0.7071, -0.4472],
        [ 0.7071, -0.8944]])


In [61]:
# 행렬의 QR factorization
Q,R = torch.qr(x)
print("Q :", Q)
print("R :", R)

Q : tensor([[-0.4472, -0.8944],
        [-0.8944,  0.4472]])
R : tensor([[-2.2361, -2.2361],
        [ 0.0000,  0.0000]])


In [62]:
# 행렬의 SVD factorization
S,V,D = torch.svd(x)
print("S :", S)
print("V :", V)
print("D :", D)

S : tensor([[-0.4472, -0.8944],
        [-0.8944,  0.4472]])
V : tensor([3.1623e+00, 5.2283e-08])
D : tensor([[-0.7071, -0.7071],
        [-0.7071,  0.7071]])
