# Lec 02. Variable and Autograd

Back propagation 을 위해 사용

In [1]:
import torch
from torch.autograd import Variable

In [2]:
x = torch.Tensor([[1, 2], [3, 4]])
x

tensor([[1., 2.],
        [3., 4.]])

In [3]:
x.sum()

tensor(10.)

Variable containing --> 변할 수 있는 값.

In [4]:
y = Variable(x, requires_grad=True)   # requires_grad=True : gradient 계산
y

tensor([[1., 2.],
        [3., 4.]], requires_grad=True)

In [5]:
y.sum() 

tensor(10., grad_fn=<SumBackward0>)

In [6]:
y.max()

tensor(4., grad_fn=<MaxBackward1>)

In [7]:
y.data  # --> 변하지 않는 값

tensor([[1., 2.],
        [3., 4.]])

In [8]:
z = 2*y + 1
z

tensor([[3., 5.],
        [7., 9.]], grad_fn=<AddBackward>)

In [9]:
print("z :", z)
print("y.requires_grad :", y.requires_grad)
print("z.requires_grad :", z.requires_grad)  # z는 y의 함수이므로 y가 변할 때 z도 함께 변한다.

print("")

print("y.grad :", y.grad) # 아직 변화된 적이 없기 때문에 None 출력됨.
print("z.grad :", z.grad)

print("")

print("y.grad_fn :", y.grad_fn)
print("z.grad_fn :", z.grad_fn)  # z = 2*y + 1 이라는 function을 가지고 있기 때문.

z : tensor([[3., 5.],
        [7., 9.]], grad_fn=<AddBackward>)
y.requires_grad : True
z.requires_grad : True

y.grad : None
z.grad : None

y.grad_fn : None
z.grad_fn : <AddBackward object at 0x0000024119DD07B8>


In [10]:
out = z.sum()
out

tensor(24., grad_fn=<SumBackward0>)

In [11]:
print("y.requires_grad :", y.requires_grad)
print("z.requires_grad :", z.requires_grad)
print("out.requires_grad :", out.requires_grad)

print("")

print("y.grad :", y.grad)
print("z.grad :", z.grad)
print("out.grad :", out.grad)

print("")

print("y.grad_fn :", y.grad_fn)
print("z.grad_fn :", z.grad_fn)
print("out.grad_fn :", out.grad_fn)

y.requires_grad : True
z.requires_grad : True
out.requires_grad : True

y.grad : None
z.grad : None
out.grad : None

y.grad_fn : None
z.grad_fn : <AddBackward object at 0x0000024119DCBC88>
out.grad_fn : <SumBackward0 object at 0x0000024119DCBDD8>


In [12]:
# By default, gradients are only retained for leaf variables. --> 첫번째 선언한 variables만 유지됨.
# non-leaf variables gradients are not retained. 
# This was done by design, to save memory.

# non-leaf variables을 보기 위해서 새로운 변수 및 함수 선언.
zGrad = torch.zeros(2,2)

def extract(z):
    global zGrad
    zGrad = z
    
z.register_hook(extract) # 이 순간의 값을 저장

In [13]:
# out으로부터 back propagation을 시작한다.... !!!
out.backward()

In [14]:
print("y.requires_grad :", y.requires_grad)
print("z.requires_grad :", z.requires_grad)
print("out.requires_grad :", out.requires_grad)

print("")

print("y.grad :", y.grad)      # y가 1 증가하면 grad는 2 증가. out.backward() 통한 역전파 값.
print("z.grad :", z.grad)      # non-leaf variables 이라서 표시 안됨.
print("out.grad :", out.grad)

print("")

print("y.grad_fn :", y.grad_fn)
print("z.grad_fn :", z.grad_fn)
print("out.grad_fn :", out.grad_fn)

print("")

print(zGrad)

y.requires_grad : True
z.requires_grad : True
out.requires_grad : True

y.grad : tensor([[2., 2.],
        [2., 2.]])
z.grad : None
out.grad : None

y.grad_fn : None
z.grad_fn : <AddBackward object at 0x0000024119DCE630>
out.grad_fn : <SumBackward0 object at 0x0000024119DCE780>

tensor([[1., 1.],
        [1., 1.]])


In [15]:
out.data

tensor(24.)